import { Response, Request } from 'express';
import TaskTypeModel from '../models/task-type.model';

export const getAllTaskType = async (req: Request, res: Response) => {
  try {
    const taskTypes = await TaskTypeModel.find();
    res.json(taskTypes);
  } catch (error) {
    res.status(500).json({
      success: false,
      message: 'Internal server error'
    }); return;
  }
}

export const createTaskType = async (req: Request, res: Response) => {
  try {
    const { name, icon, isActive, isSubTask } = req.body;

    const existingTaskType = await TaskTypeModel.findOne({ name: name.trim() });
    if (existingTaskType) {
      res.status(400).json({
        success: false,
        message: 'Task type with this name already exists'
      });
      return;
    }

    const autoGeneratedCode = name.trim().toUpperCase().replace(/\s+/g, '_').replace(/[^A-Z0-9_]/g, '');

    const newTaskType = new TaskTypeModel({
      name: name.trim(),
      code: autoGeneratedCode,
      icon: icon || '',
      isActive: isActive !== undefined ? isActive : true,
      isSubTask: isSubTask !== undefined ? isSubTask : false
    });

    const savedTaskType = await newTaskType.save();

    res.status(201).json({
      success: true,
      message: 'Task type created successfully',
      data: savedTaskType
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: 'Internal server error'
    }); return;
  }
}